<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ArcademiaEngine.Core\ArcademiaEngine.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType> 
  </PropertyGroup>


  <PropertyGroup>
    <DefineConstants>$(DefineConstants);DESKTOP</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <!-- Recursively grabs all files from the solution-level Resources folder -->
    <Content Include="$(MSBuildThisFileDirectory)..\Resources\**\*.*">
      <Link>Resources\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
