<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <WasmMainJSPath>main.js</WasmMainJSPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

  <ItemGroup>
    <None Include="runtimeconfig.template.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Raylib-cs\Raylib-cs.csproj" />
    <ProjectReference Include="..\ArcademiaEngine.Core\ArcademiaEngine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <WasmExtraFilesToDeploy Include="index.html" />
    <WasmExtraFilesToDeploy Include="main.js" />
  </ItemGroup>

  <ItemGroup>
    <NativeFileReference Include="wasm\native\raylib.a" />
    <WasmFilesToIncludeInFileSystem Include="Resources\**\*.*" TargetPath="Resources\%(RecursiveDir)\%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <EmccFlags>-s USE_GLFW=3 -O3</EmccFlags>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <WasmEmitSymbolMap>true</WasmEmitSymbolMap>
    <EmccFlags>-sUSE_GLFW=3 -sVERBOSE=1 -O2 -g3 -sINITIAL_MEMORY=128MB -sMAXIMUM_MEMORY=2048MB -sALLOW_MEMORY_GROWTH=1</EmccFlags>
  </PropertyGroup>
  
</Project>